// box_inc_poison

// Written by Box
// Include file for poison constants

// THIS IS FOR TESTING PURPOSES ONLY, DO NOT EDIT THIS FILE

int POISON_MINE_1 = 500;
int POISON_MINE_2 = 500;
int POISON_MINE_3 = 500;
int POISON_MINE_4 = 500;
int POISON_MINE_5 = 500;
int GAS_GRENADE = 500;
int RADIATION_ROCKET = 500;
