import shutil


weapons = []
# Generated lines go here
#WEAPONS

def write_header(file, weapons):
	file.write('; This file was generated by weapgen.py\n')
	file.write('\n')
	file.write('[Settings]\n')
	file.write('FileExists=1\n')
	file.write('ConfirmMessage=N/A\n')
	file.write('LogLevel=4\n')
	file.write('InstallerMode=1\n')
	file.write('BackupFiles=0\n')
	file.write('PlaintextLog=1\n')
	file.write('LookupGameFolder=1\n')
	file.write('LookupGameNumber=2\n')
	file.write('SaveProcessedScripts=0\n')
	file.write('\n')
	file.write('[TLKList]\n')
	file.write('\n')
	file.write('[InstallList]\n')
	file.write('\n')
	file.write('[2DAList]\n')
	file.write('\n')
	file.write('[GFFList]\n')
	for i in range(0, len(weapons)):
		file.write('File')
		file.write(str(i+1))
		file.write('=')
		file.write(weapons[i].name)
		file.write('.uti\n')
	file.write('\n')
	file.write('[CompileList]\n')
	file.write('\n')
	file.write('[SSFList]\n')
	file.write('\n')


def write_weap(file, weap, ):
	file

with open('tslpatchdata\\eweap.ini', 'w') as file:
	write_header(file, weapons)
	for weap in weapons:
		for n in range(1, 21):
			write_weap(file, hide, n)
			shutil.copy('template.uti', 'tslpatchdata\\' + weap + str(n) +'.uti')
