// box_inc_poison

// Written by Box
// Include file for poison constants

int POISON_MINE_1 = #BOXP_POISON_MINE_1#;
int POISON_MINE_2 = #BOXP_POISON_MINE_2#;
int POISON_MINE_3 = #BOXP_POISON_MINE_3#;
int POISON_MINE_4 = #BOXP_POISON_MINE_4#;
int POISON_MINE_5 = #BOXP_POISON_MINE_5#;
int GAS_GRENADE = #BOXP_GAS_GRENADE#;
int RADIATION_ROCKET = #BOXP_RADIATION_ROCKET#;
int POISON_DART = #BOXP_POISON_DART#;
